version: '3'
services:
  ssserver:
    container_name: ssserver
    image: prince/shadowsocks:latest
    ports:
      - 8388:8388
    volumes:
      - ./config:/etc/shadowsocks
    environment:
      - mode=server
